language: python
python:
  - "2.7"
before_install:
    - "pip install -r requirements.txt"
env:
    global:
        - PYTHONPATH="/home/travis/build/mpolednik/script.kodi.hue.ambilight/resources/lib"

script:
    - py.test -v
